[#32] Unflatten Function
jessie-codes/safe-flat pull request #35
Opened 2020-10-05 01:26 UTC by rpartha

### :pencil2: Change Description

Add an unflatten function that will take a flattened object and return a nested object.
New version of now exports an object containing both flatten and unflatten functions.

### :link: Relates to Issue

Fixes # 32

### :triangular_flag_on_post: Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### :heavy_check_mark: Pull Request Checklist

- [x] Adherence to the  [Developer Certificate of Origin (DCO)](https://developercertificate.org/) version 1.1 (`git --signoff`).
- [x] Commits follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) standard.
- [x] Ensure all tests are passing (`npm test`).
- [x] Adhere to [standardjs](http://standardjs.com) guidelines.
- [x] Add tests for any new features or to show that bugs have been fixed.
- [x] Update the README.md with details of changes to the interface.

2020-10-05 16:08 UTC, jessie-codes commented
Thank you for submitting this PR! I will review it this evening.

2020-10-05 21:31 UTC, jessie-codes requested changes
Overall, this looks great, but it needs a couple of updates.

1. Your commit message doesn't follow the `conventional commits` standard. It should start with `feat:` and not `feat: feat:` (notice the duplicate prefix)
2. This code doesn't match the `standardjs` ruleset. If you issue the command `npm run lint` it should show you what needs to be changed.

2020-10-06 01:06 UTC, rpartha commented
@jessie-codes I've addressed the changes.

2020-10-06 01:18 UTC, jessie-codes approved these changes

2020-10-06 01:21 UTC, merged